vertex/app/admin/views.py
# vertex/app/admin/views.py
"""
Views for the "admin" blueprint.
"""
from functools import wraps
import datetime
import io
import os

from flask import (
	Blueprint, 
	render_template,
	flash,
	redirect,
	url_for,
	abort,
	request,
	current_app,
	Response,
	make_response,
	request,
)

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PIL import Image
import numpy as np
import datetime
from dateutil.relativedelta import relativedelta

from io import BytesIO
from xhtml2pdf import pisa

from flask_login import login_user, current_user, logout_user

from .forms import (
	is_empty,
	EditEmail,
	EditName,
	AdminLogin,
	EditFacility,
	EditClass,
	NewUser,
	NewFacility,
	NewClass,
	EditMembership,
	NewMembership,
	EditDiscount,
	NewDiscount
)

from app import models
from app.models import db

blueprint = Blueprint("admin", __name__, static_folder="../static")

def manager_login_required(func):
	"""
	Custom wrapper function for verifying that a manager is logged in.
	If access is denied, 401 error.

	Used as follows:	
	@manager_login_required
	def some_func():
		print("This will only run if a manager is logged in")
	"""
	@wraps(func)
	def wrapper(*args, **kwargs):
		if not ("LOGIN_DISABLED" in current_app.config):
			if current_user.is_anonymous or current_user.user_type != "manager":
				abort(401) # Exits the function - access denied
		return func(*args, **kwargs)
	return wrapper


@blueprint.route("/admin/", methods=["GET"])
@manager_login_required
def index():
	"""
	Route to manager homepage.
	"""
	if not (current_user.is_authenticated and current_user.user_type == "manager"):
		return redirect(url_for("admin.login"))
	
	id = current_user.id
	manager = current_user.user_type == "manager"
	return render_template("manager_index.html", title="Manager Home | Vertex", id=id, manager=manager)

# Manager login route
@blueprint.route('/admin/login', methods=['GET','POST'])
def login():
	"""
	Route to manager login page.
	"""
	form = AdminLogin()
	if form.validate_on_submit():
		email = form.email.data
		password = form.password.data
		manager = models.Users.query.where(models.Users.email == email, models.Users.user_type == "manager").first()
		if manager:
			if manager.verify_password(password):
				flash('Logged in successfully!', category='success')
				login_user(manager, remember=False)
				current_app.logger.info("Logged in manager having user ID " + str(current_user.id) + " successfully on " + str(datetime.datetime.now()))
				return redirect(url_for('admin.index'))
			else:
				flash('Incorrect password, try again.', category='danger')
				current_app.logger.info("Invalid login attempt for manager access using email " + email + " on " + str(datetime.datetime.now()))
		else:
			flash('Manager account does not exist.', category='danger')

	return render_template("manager_login.html", title="Manager Login | Vertex", user=current_user, form=form)

# Views related to admin user management
@blueprint.route("/admin/users", methods=["GET"])
@manager_login_required
def users():
	"""
	Route to manager view users page.
	"""
	userObjs = models.Users.query.order_by(models.Users.id).all()
	users = []

	for user in userObjs:
		users.append(user.get_dict())
	
	return render_template("manager_users.html", title="User Management - Manager View | Vertex", users=users)

@blueprint.route("/admin/delete_user/<int:id>", methods=["GET"])
@manager_login_required
def delete_user(id):
	"""
	Route for manager to delete a user.
	"""
	confirm = request.args.get("confirm")
	if confirm:
		target = models.Users.query.where(models.Users.id == id).first()
		if not target:
			return render_template("message.html", message="No such user. Redirecting...", redirect=url_for("admin.users"))
		
		if target.id == current_user.id:
			return render_template("message.html", message="Cannot delete user currently logged in. Redirectiong...", redirect=url_for("admin.edit_user", id=id))

		facility_bookings = models.FacilityBookings.query.where(models.FacilityBookings.user_id == id).all()
		for booking in facility_bookings:
			db.session.delete(booking)

		class_bookings = models.ClassBookings.query.where(models.ClassBookings.user_id == id).all()
		for booking in class_bookings:
			db.session.delete(booking)

		db.session.delete(target)
		try:
			db.session.commit()
			flash(f"User {id} deleted.", category="success")
			current_app.logger.info("User ID " + str(id) + " deleted successfully on " + str(datetime.datetime.now()))
			return redirect(url_for("admin.users"))
		except Exception as e:
			current_app.logger.error(e)
			db.session.rollback()
			flash(f"Deletion failed. Database error {repr(e)}", category="danger")
			current_app.logger.info("User ID " + str(id) + " unable to delete on " + str(datetime.datetime.now()))

	return render_template("manager_delete.html", title="Delete User - Manager View | Vertex", target="user", id=id)

@blueprint.route("/admin/reset/<int:id>", methods=["GET"])
def reset_password(id):
	"""
	Route for manager to reset password.
	"""
	confirm = request.args.get("confirm")
	if confirm:
		target = models.Users.query.where(models.Users.id == id).first()
		if not target:
			return render_template("message.html", title="Redirect | Vertex", message="No such user. Redirecting...", redirect=url_for("admin.users"))
		
		target.reset_password("default") # Reset the user's password to 'default'

		try:
			db.session.commit()
			flash(f"User {id} password reset to 'default'.", category="success")
			current_app.logger.info("User ID " + str(id) + " password reset by manager successfully on " + str(datetime.datetime.now()))
			return redirect(url_for("admin.users"))
		except Exception as e:
			current_app.logger.error(e)
			db.session.rollback()
			flash(f"Password reset failed. Database error {repr(e)}", category="danger")
			current_app.logger.info("User ID " + str(id) + " unable to password reset by manager on " + str(datetime.datetime.now()))

	return render_template("manager_reset_password.html", title="Reset Password - Manager View | Vertex", id=id)

@blueprint.route("/admin/edit/<int:id>", methods=["GET"])
@manager_login_required
def edit_user(id):
	"""
	Route for manager to edit user.
	"""
	user = models.Users.query.where(models.Users.id == id).first()
	if not user:
		flash(f"User {id} not found", "danger")
		return redirect(url_for("admin.users"))

	user = user.get_dict()
	edit_email = EditEmail()
	edit_name = EditName()

	return render_template(
		"manager_edit_user.html", 
		title="Edit user " + str(id), 
		user=user, 
		edit_email=edit_email,
		edit_name=edit_name
	)

@blueprint.route("/admin/edit_email/<int:id>", methods=["POST"])
@manager_login_required
def edit_email(id):
	"""
	Route for manager to edit email.
	"""
	user = models.Users.query.where(models.Users.id == id).first()
	if not user:
		flash(f"Edit email error: user {id} not found", "danger")
		current_app.logger.info("User ID " + str(id) + " not found for edit on " + str(datetime.datetime.now()))
		return redirect(url_for("admin.users"))

	edit_email = EditEmail()
	if edit_email.validate_on_submit():
		user.email = edit_email.new_email.data
		db.session.add(user)
		try:
			db.session.commit()
		except Exception as e:
			current_app.logger.error(e)
			db.session.rollback()
			flash(f"DB failed to commit user email: {repr(e)}", "danger")
			current_app.logger.info("User ID " + str(id) + " unable to edit due to database error on " + str(datetime.datetime.now()))
			return redirect(url_for("admin.edit_user", id=id))
		
		flash(f"Edited user {user.id}'s email", "success")
		current_app.logger.info("User ID " + str(id) + " edited email successfully on " + str(datetime.datetime.now()))
		return redirect(url_for("admin.edit_user", id=id))

	return redirect(url_for("admin.edit_user", id=id))

@blueprint.route("/admin/edit_name/<int:id>", methods=["POST"])
@manager_login_required
def edit_name(id):
	"""
	Route for manager to edit name.
	"""
	user = models.Users.query.where(models.Users.id == id).first()
	if not user:
		flash(f"Edit name error: user {id} not found", "danger")
		current_app.logger.info("User ID " + str(id) + " not found for edit on " + str(datetime.datetime.now()))
		return redirect(url_for("admin.users"))

	edit_name = EditName()
	if edit_name.validate_on_submit():
		user.firstname = edit_name.new_firstname.data
		user.lastname = edit_name.new_lastname.data
		db.session.add(user)
		try:
			db.session.commit()
			flash(f"Edited user {user.id}'s name", "success")
			current_app.logger.info("User ID " + str(id) + " name edited successfully on " + str(datetime.datetime.now()))
		except Exception as e:
			current_app.logger.error(e)
			db.session.rollback()
			flash(f"DB failed to commit user name: {repr(e)}", "danger")
			current_app.logger.info("User ID " + str(id) + " unable to edit name due to database error on " + str(datetime.datetime.now()))

	return redirect(url_for("admin.edit_user", id=id))

# Views related to admin facility management
@blueprint.route("/admin/facilities", methods=["GET"])
@manager_login_required
def facilities():
	"""
	Display facility information to the manager.
	"""
	# Query the facility objects from the table
	facilityObjs = models.Facilities.query.order_by(models.Facilities.id).all()

	# Create a list of facility dictionaries
	facilities = [o.get_dict() for o in facilityObjs]

	# Render template
	return render_template("manager_facilities.html", title="Facilities - Manager View | Vertex", facilities=facilities)

@blueprint.route("/admin/edit_facility/<int:id>", methods=["GET", "POST"])
@manager_login_required
def edit_facility(id):
	"""
	Route for manager to edit facility.
	"""
	facility = models.Facilities.query.where(models.Facilities.id == id).first()
	if not facility:
		flash(f"Edit facility error: facility {id} not found", "danger")
		current_app.logger.info("Facility ID " + str(id) + " not found for edit on " + str(datetime.datetime.now()))

vertex/app/templates/401.html
<!-- templates/401.html -->
<!-- Custom Error landing page -->

<!-- based on -->
<!-- https://flask.palletsprojects.com/en/1.1.x/patterns/errorpages/ -->

<!-- Code to indicate this will extend the base.html page -->
{% extends "base.html" %}

<!-- Block content to be substituted -->
{% block content %}

<div class="ml-5 mt-5 mr-5">

<div class="jumbotron">
  <h1 class="display-4">Access Denied</h1>
  <p class="lead">Looks like you don't have the necessary credentials to access this page. Time to redirect you to the right page!</p>
  <p>Error Code: 401</p>
  <p class="lead">
    <a href="{{url_for('public.index')}}">
      <button type="button" onclick='' class="btn btn-outline-primary btn-sm">Return to Homepage</button>
    </a>
  </p>
</div>

</div>

{% endblock %}

vertex/app/templates/base.html
<!-- templates/base.html -->
<!-- Base HTML template page extended by all other webpages -->

<!DOCTYPE html>
<html lang="en">

<!-- PAGE HEADER -->

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom asset management -->
    <!-- <link href="../static/css/styles.css" rel="stylesheet"> -->
    {% assets "js_all" -%}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {%- endassets %}
    {% assets "css_all" -%}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {%- endassets %}

    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.5/index.global.min.js"></script>
    <!-- Font Awesome CDN -->
    <script src="https://kit.fontawesome.com/930f5d5df2.js" crossorigin="anonymous"></script>

    <!-- FAVICON-->
    <link rel="icon" type="image/x-icon" href="../static/images/favicon.ico">
    <!-- PAGE TITLE -->
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>No title</title>
    {% endif %}

</head>


<!-- PAGE BODY -->

<body>

<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
}
</script>

<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    {% if current_user.user_type != 'manager' %}
    <!-- Bootstrap Navigation Bar -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">

        <!-- Brand/logo -->
        <a class="navbar-brand" style="padding-left: 10px;" href="/">
            <img src="/static/images/logo.jpeg" alt="Logo" style="width: 40px; height: 40px;">
        </a>
        <a class="navbar-brand" href="/">Vertex Sports</a>
    

        <!-- Navbar -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="/">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                        <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
                      </svg>  
                    Home
                    </a>

                <!-- Show the following only if user is logged in -->
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="/facilities">Facilities</a>
                <a class="nav-item nav-link" href="/classes">Classes</a>
                <a class="nav-item nav-link" href="/bookings">Bookings</a>
                <a class="nav-item nav-link" href="/my_memberships">Membership</a>
                <a class="nav-item nav-link" href="/logout">Logout</a>
                {% endif %}
                
            </div> 
            <!--Search Box-->
            <div class="ml-auto">
                <form class="form-inline my-2 my-lg-0" action="/" method="GET">
                    <div class="mr-sm-2">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" id="searchInput">
                    <button class="btn btn-success" type="button" onclick="search()">Search</button>
                </div>
                </form>
            </div>


            <script>
                function search() {
                    var query = document.getElementById('searchInput').value;
                    var url = 'http://127.0.0.1:5000/' + query.toLowerCase();
                    console.log('search query:', query);
                    console.log('redirecting to:', url);
                    window.location.href = url;
                }
            </script>

            {% if not current_user.is_authenticated %}
                <!--Dropdown menu for login and sign up for users-->
                <div class="dropdown">
                    <button class="nav-item ml-auto btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa-regular fa-user"></i> Sign Up / Login
                    </button>
                    <div class="nav-item dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="/customer-signup">Customer Sign Up</a>
                      <a class="dropdown-item" href="/login">Customer Login</a>
                      <!-- 
                      <a class="dropdown-item" href="/employee-login">Employee Login</a>
                      <a class="dropdown-item" href="/admin/login">Manager Login</a>
                    -->
                    </div>
                  </div>
                  {% endif %}
                  <div id="google_translate_element" class="text-right"></div>
            
        </div>

    </nav>
    {% endif %}

    <!-- MANAGER NAVBAR -->
    {% if current_user.user_type == 'manager' %}
    <!-- Bootstrap Navigation Bar -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">

        <!-- Brand/logo (to be added when logo is finalized) -->
        <a class="navbar-brand" href="/">
            <img src="/static/images/logo.jpeg" alt="Logo" style="width: 40px;">
        </a>
        <a class="navbar-brand" href="/">Vertex Sports</a>

        <!-- Navbar -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href=" {{ url_for('admin.index') }}">Home<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="/logout">Logout</a>

            </div>

        </div>

    </nav>
    {% endif %}


    <!-- FLASHED MESSAGES -->
    {% if current_user.user_type != 'manager' %}
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% endif %}

    {% if current_user.user_type == 'manager' %}
    <!-- Manager Sidenav -->
    <!-- based on ideas from -->
    <!-- https://www.w3schools.com/howto/howto_css_fixed_sidebar.asp -->
    <div class="sidenav">
        <a href="#about"></a>
        <h2 class="sidebar_heading">Manage</h2>
        <a href=" {{ url_for('admin.users') }}">Users</a>
        <a href=" {{ url_for('admin.classes') }}">Classes</a>
        <a href=" {{ url_for('admin.facilities') }}">Facilities</a>
        <a href=" {{ url_for('admin.memberships') }}">Memberships</a>
        <a href=" {{ url_for('admin.discount') }}">Discounts</a>
        <h2 class="sidebar_heading">Analyze</h2>
        <a href=" {{ url_for('admin.analytics_facilities') }}">Facilities Stats</a>
        <a href=" {{ url_for('admin.analytics_classes') }}">Classes Stats</a>
        <a href=" {{ url_for('admin.analytics_membership') }}">Membership Stats</a>
        <a href=" {{ url_for('admin.sales') }}">Sales Stats</a>
        <a href=" {{url_for('admin.logout')}} ">Logout</a>
    </div>
    {% endif %}

    <!-- PAGE BODY BLOCK CONTENT -->
    {% block content %}
    {% endblock %}



    <!-- Custom Javascript -->
    <script src="../static/js/javascript.js"></script>

    <!-- Optional JavaScript for Bootstrap-->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>

    <!-- Font Awesome CDN -->
    <script src="https://kit.fontawesome.com/930f5d5df2.js" crossorigin="anonymous"></script>

    <!-- This document validates as CSS level 3 + SVG -->
    <div class="ml-5 mr-5">
        <p>
            <a href="http://jigsaw.w3.org/css-validator/check/referer">
                <img text-align=center style="border:0;width:88px;height:31px"
                    src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!" />
            </a>
        </p>
    </div>

</body>
<!-- FOOTER -->
<footer class="text-lg-start bg-dark text-muted">
    <div class="text-right">
    <a type="button" class="btn btn-success" href="/employee-login">Employee Login</a>
    <a type="button" class="btn btn-success" href="/admin/login">Manager Login</a>
</div>
    <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    Copyright © 2023. All rights reserved. Privacy Policy </div>
  <!-- Copyright -->
</footer>

</html>

vertex/app/templates/confirmation.html
<!-- Code to indicate this will extend the base.html page -->
{% extends "base.html" %}

{% block content %}

<div class="background-image"></div>
	<div class="transparent-column">
    <h1>You have booked the {{facility_name}}</h1>

    <form action="" method="post" name="confirmation-details">
        {{ form.hidden_tag() }}

        {% if current_user.user_type == "employee" %}
            <p> <!-- User booked-->
                <label for="user_booked">Enter Customer Email</label>
                {{ form.user_booked(placeholder="User's email") }}<br>
                {% for error in form.user_booked.errors %}
                    [{{ error }}]
                {% endfor %}
            </p>
        {% endif %}

        <p> <!--Activities-->
            <label for="activity">What activity would you like to do in the {{facility_name}}?</label>
            {{ form.activity }}<br>
            {% for error in form.activity.errors %}
                [{{ error }}]
            {% endfor %}
        </p>
       
        <p> <!--date chosen-->
            <label for="date_chosen">What date would you like to book?</label>
            {{ form.date_chosen }}<br>
            {% for error in form.date_chosen.errors %}
                [{{ error }}]
            {% endfor %}
        </p>
    
        <p> <!--Start times-->
            <label for="start_time">What time would you like to start?</label>
            {{ form.start_time }}<br>
            {% for error in form.start_time.errors %}
                [{{ error }}]
            {% endfor %}
        </p>

        <p> <!--End times-->
            <label for="end_time">What time would you like to end?</label>
            {{ form.end_time }}<br>
            {% for error in form.end_time.errors %}
                [{{ error }}]
            {% endfor %}
        </p>
        <button type="submit" class="btn btn-success">Pay for the class</button>
    </form>
</div>

{% endblock %}

vertex/app/templates/custom_error_page.html
<!-- templates/500.html -->
<!-- Custom Error landing page -->

<!-- based on ideas from -->
<!-- https://flask.palletsprojects.com/en/1.1.x/patterns/errorpages/ -->

<!-- Code to indicate this will extend the base.html page -->
{% extends "base.html" %}

<!-- Block content to be substituted -->
{% block content %}

<div class="ml-5 mt-5 mr-5">

        <div class="jumbotron">
          <h1 class="display-4">{{ name }}</h1>
          <p class="lead">Oops! Something went wrong. In the meantime, you can try refreshing the page or navigating back to the previous page. </p>
          <p class="lead">
            <a href="{{url_for('public.index')}}">
              <button type="button" onclick='' class="btn btn-outline-primary btn-sm">Return to Homepage</button>
            </a>
          </p>
        </div>
</div>

{% endblock %}

vertex/app/templates/email_template.html
<!-- vertex/app/templates/email_confirmation.html -->

<!-- This is a template for the email to be sent, not for a HTML page. -->

<!DOCTYPE html>
<html lang="en">

<!-- PAGE HEADER -->

<head>
</head>

<!-- PAGE BODY -->

<body>

<div class="jumbotron">
    <h1 class="display-4">Welcome to Vertex!</h1>
    <p class="lead">Thanks for signing up to Vertex.</p>
    <hr class="my-4">
    <p>Please click here to confirm your email address:</p>
    <p class="lead">
      <a href="{{ confirm_url }}">
        <button type="button" class="btn btn-outline-primary btn-sm">Confirm my Email</button>
      </a>
    </p>
  </div>
</body>

</html>

vertex/app/templates/manager_analytics_facilities.html
<!-- Code to indicate this will extend the base.html page -->
{% extends "base.html" %}

<!-- Block content to be substituted on the index.html page -->
{% block content %}

</div>

<!-- Content of the page -->
<div class="main_manager_content" id="main-manager-body">
	<div class="m-5">

		{% with messages = get_flashed_messages(with_categories=True) %}
		{% if messages %}
		{% for category, message in messages %}
		<div class="alert alert-{{category}}" role="alert">
			{{ message }}
		</div>
		{% endfor %}
		{% endif %}
		{% endwith %}

		<a href="{{url_for('admin.index')}}">
			<button type="button" class="btn btn-outline-primary btn-sm">Return to admin index</button>
		</a>


		<h3> Manager Analytics - Facilities</h3>

		<a href="{{url_for('admin.download_facilities')}}">
            <button type="button" class="btn btn-success">Download PDF Report</button>
        </a>

		<h2>Usage statistics of the Climbing Wall over the last week</h2>
		<img src="/plots/2" alt="Climbing Wall Stats">

		<h2>Usage statistics of the Fitness Room over the last week</h2>
		<img src="/plots/3" alt="Sports Hall Stats">

		<h2>Usage statistics of the Sports Hall over the last week</h2>
		<img src="/plots/4" alt="Sports Hall Stats">

		<h2>Usage statistics of the Squash Courts over the last week</h2>
		<img src="/plots/5" alt="Squash Courts Stats">

		<h2>Usage statistics of the Studio over the last week</h2>
		<img src="/plots/6" alt="Studio Stats">

		<h2>Usage statistics of the Swimming pool over the last week</h2>
		<img src="/plots/7" alt="Swimming Pool Stats">


	</div>
</div>
{% endblock %}

vertex/app/templates/manager_reset_password.html
<!-- Code to indicate this will extend the base.html page -->
{% extends "base.html" %}

<!-- Block content to be substituted on the index.html page -->
{% block content %}

</div>

<!-- Content of the page -->
<div class="main_manager_content">
<div class="ml-5 mt-5">
	{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
	

	<h3>
		Are you sure you want to reset password for user {{id}}?
	</h3>

	<br>
	
	<h6>
		Password will be reset to 'default'.
	</h6>
	<br>

	<a href="{{ url_for('admin.edit_user', id=id) }}">
		<button role="button" class="btn btn-primary btn">Cancel</button>
	</a>
	<a href=" {{ url_for('admin.reset_password', id=id, confirm=True) }} ">
		<button role="button" class="btn btn-outline-danger btn">Reset</button>
	</a>

	<br>
</div>
</div>

{% endblock %}